version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      # Imagine these credentials are kept secret
      POSTGRES_USER: unacceptableurgently
      POSTGRES_PASSWORD: TjK2GbrgP*b%jr#r
      POSTGRES_DB: event-management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
